Use new XP-Runners Update project name to "XP-Framework Maven plugin"

diff --git a/src/main/resources/net/xp_framework/runners/unix/xpws b/src/main/resources/net/xp_framework/runners/unix/xpws
--- a/src/main/resources/net/xp_framework/runners/unix/xpws
+++ b/src/main/resources/net/xp_framework/runners/unix/xpws
@@ -66,7 +66,40 @@ locate() {
   if [ $expect = 1 ] ; then echo "*** Failed to locate $file in $path" >&2 ; fi
   echo ""
 }
-base="$DIRNAME" RUNNER="class" INCLUDE="." xppath="$DIRNAME" ARGS=xp.compiler.Runner IFS="|";
+RUNNER=web
+TOOL=
+SERVER_PROFILE=dev
+while [ $# != 0 ]; do
+  case $1 in
+    -p)
+      SERVER_PROFILE=$2
+      shift 2
+      ;;
+    -r)
+      DOCUMENT_ROOT=$2
+      root="-t|$2|"
+      shift 2
+      ;;
+    -?)
+      RUNNER=class
+      TOOL="xp.scriptlet.Usage|xpws.txt"
+      break
+      ;;
+    *:*)
+      server=${1%:*}
+      port=${1#*:}
+      shift 1
+      break
+      ;;
+    *)
+      server=$1
+      shift 1
+      break
+      ;;
+  esac
+done
+ADDR=${server-localhost}:${port-8080}
+base="$DIRNAME" RUNNER=$RUNNER INCLUDE="." xppath="$DIRNAME" ARGS=$TOOL IFS="|";
 ifs="|"
 if [ "" = "$USE_XP" ] ; then
   unset USE_XP
@@ -135,4 +168,19 @@ args="-C${ifs}-q${ifs}-dinclude_path=\".$PATHSEP$USE_XP$PATHSEP$PATHSEP$INCLUDE\
 tool=$(locate "$USE_XP" "tools/"${RUNNER}".php" 1)
 export XP_EXE
 IFS="|"
-${XP_EXE}${ifs}${args}${ifs}$tool ${ARGS} "$@"
+if [ $RUNNER = class ] ; then
+  ${XP_EXE}${ifs}${args}${ifs}$tool ${ARGS} "$@"
+else
+  if [ ! -e "etc/web.ini" ] ; then
+    echo "*** Cannot find the web configuration web.ini in etc/, exiting." >&2
+    exit 3
+  fi
+  export SERVER_PROFILE
+  export DOCUMENT_ROOT
+  ${XP_EXE}${ifs}-S${ifs}${ADDR}${ifs}${root}${args}${ifs}$tool ${ARGS} "$@" &
+  PID=$!
+  echo "[xpws-$SERVER_PROFILE#$PID] running $ADDR. Press <Enter> to exit"
+  read enter
+  echo "[xpws-$SERVER_PROFILE#$PID] shutting down..."
+  kill -TERM $PID
+fi
